// Identity data external; generated by scripts/build_rmm_queries.py; rules 1.1.0; mode report; view all.
// Rule SHA256: e2129f816ef1d0609e8a5f8c0cb3ce9ff5f6afc23be9a5c3c4366d7736cab1d0; config SHA256: f75c4ff1f69b813a1e3170e2d0d903a16469c914750766db5e062f1ce5a26f2f.
// Event counts precede IOC association; collection fields are independent sets.
// Official references and usage: README.md. Validate Cortex with a 1h window.
config case_sensitive = true timeframe = 7d
| dataset = xdr_data
| filter action_external_hostname != null or action_remote_ip != null
| alter remote_host = lowercase(rtrim(if(action_external_hostname != null and action_external_hostname != "", action_external_hostname, to_string(action_remote_ip)), ".")),
        _rule_name = lowercase(coalesce(actor_process_image_name, "")),
        _rule_path = if(actor_process_image_path ~= "^[A-Za-z]:", lowercase(replex(actor_process_image_path, "[\\\\]", "/")), coalesce(actor_process_image_path, "")),
        _rule_signer = lowercase(coalesce(actor_process_signature_vendor, "")),
        _rule_device_name = lowercase(coalesce(agent_hostname, "")),
        _rule_sha256 = lowercase(coalesce(actor_process_image_sha256, "")),
        _signature_valid = if(actor_process_signature_status = null, null, if(actor_process_signature_status = 1, true, false))
| filter remote_host != ""
| alter _health_key = 1
| join type = left conflict_strategy = left (
    dataset = rmm_tool_profiles
    | filter release in (dataset = rmm_tool_profiles | filter record_type = "manifest" | sort desc release | limit 1 | fields release)
    | comp count() as _profile_rows, count_distinct(process_name) as _profile_keys,
        count_distinct(release_digest) as _profile_digests,
        sum(if(record_type = "manifest", 1, 0)) as _profile_markers,
        max(to_integer(expected_rows)) as _expected_rows, max(release) as profile_version
    | alter ProfileOK = if(_profile_rows = add(_expected_rows, 1) and _profile_keys = add(_expected_rows, 1)
        and _expected_rows > 0 and _profile_markers = 1 and _profile_digests = 1, true, false)
    | alter report_status = if(ProfileOK = true, "ok", "profile_data_unavailable"), _health_key = 1
) as health _health_key = health._health_key
| join type = left conflict_strategy = left (
    dataset = rmm_tool_profiles
    | filter record_type = "profile" and release in (
        dataset = rmm_tool_profiles | filter record_type = "manifest" | sort desc release | limit 1 | fields release)
    | fields tool_id as _profile_id, tool_name as _profile_tool, process_name as _profile_name,
        signers as _profile_signers, software_role as _profile_role, ioc_names as _profile_iocs
    | dedup _profile_name
) as profile _rule_name = profile._profile_name
| alter DetectedTool=coalesce(_profile_tool, ""), DetectedToolId=coalesce(_profile_id, ""),
    SoftwareRole=coalesce(_profile_role, ""), ExpectedSigners=coalesce(_profile_signers, ""),
    IdentityIocNames=coalesce(_profile_iocs, "")
| alter IdentityBasis=if(DetectedToolId != "", "file_name", ""), IdentityConflict=false,
    EvidenceLevel=if(DetectedToolId = "", "domain_only", if(_signature_valid = true and _rule_signer != ""
        and ExpectedSigners contains concat(";", _rule_signer, ";") and SoftwareRole != "dual_use" and report_status = "ok", "supported_identity", "software_candidate"))
| alter DefaultRuleIds = concat(if(((((_rule_name != null and _rule_name != "" and (_rule_name = "chrome.exe")))
                and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:/(?:program files(?: \(x86\))?|users/[^/]+/appdata/(?:local|roaming))/(?:[^/]+/)*google/(?:[^/]+/)*chrome[.]exe$")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "google (?:llc|inc)"))))
            or (((_rule_name != null and _rule_name != "" and (_rule_name = "msedge.exe")))
                and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:/(?:program files(?: \(x86\))?|users/[^/]+/appdata/(?:local|roaming))/(?:[^/]+/)*microsoft/edge/(?:[^/]+/)*msedge[.]exe$")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "microsoft corporation"))))
            or (((_rule_name != null and _rule_name != "" and (_rule_name = "firefox.exe")))
                and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:/(?:program files(?: \(x86\))?|users/[^/]+/appdata/(?:local|roaming))/(?:[^/]+/)*mozilla firefox/(?:[^/]+/)*firefox[.]exe$")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "mozilla corporation"))))
            or (((_rule_name != null and _rule_name != "" and (_rule_name = "vivaldi.exe")))
                and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:/(?:program files(?: \(x86\))?|users/[^/]+/appdata/(?:local|roaming))/(?:[^/]+/)*vivaldi/(?:[^/]+/)*vivaldi[.]exe$")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "vivaldi technologies"))))
            or (((_rule_name != null and _rule_name != "" and (_rule_name = "qqbrowser.exe")))
                and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:/(?:program files(?: \(x86\))?|users/[^/]+/appdata/(?:local|roaming))/(?:[^/]+/)*tencent/qqbrowser/(?:[^/]+/)*qqbrowser[.]exe$")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "tencent technology"))))
            or ((_rule_name != null and _rule_name != "" and (_rule_name in ("sogouexplorer.exe")))
                and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:/program files(?: \(x86\))?/sogou/sogouexplorer/(?:[^/]+/)*sogouexplorer[.]exe$")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "^(?:beijing sogou technology development co[.]?,? ltd[.]?|tencent technology ?\(shenzhen\) company limited)$"))))
            or ((_rule_name != null and _rule_name != "" and (_rule_name in ("google chrome", "google chrome helper", "google chrome helper (renderer)", "google chrome helper (gpu)", "google chrome helper (plugin)")))
                and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "(?i)^/(?:applications|users/[^/]+/applications)/google chrome[.]app/contents/(?:macos/google chrome|frameworks/google chrome framework[.]framework/versions/[^/]+/helpers/google chrome helper(?: \((?:renderer|gpu|plugin)\))?[.]app/contents/macos/google chrome helper(?: \((?:renderer|gpu|plugin)\))?)$")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "^(?:developer id application: )?google (?:llc|inc)(?: \([a-z0-9]+\))?$"))))
            or ((_rule_name != null and _rule_name != "" and (_rule_name in ("microsoft edge", "microsoft edge helper", "microsoft edge helper (renderer)", "microsoft edge helper (gpu)", "microsoft edge helper (plugin)")))
                and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "(?i)^/(?:applications|users/[^/]+/applications)/microsoft edge[.]app/contents/(?:macos/microsoft edge|frameworks/microsoft edge framework[.]framework/versions/[^/]+/helpers/microsoft edge helper(?: \((?:renderer|gpu|plugin)\))?[.]app/contents/macos/microsoft edge helper(?: \((?:renderer|gpu|plugin)\))?)$")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "^(?:developer id application: )?microsoft corporation(?: \([a-z0-9]+\))?$"))))), "rpt-browser-standard;", ""),
         if((((_rule_name != null and _rule_name != "" and (_rule_name in ("ima.copilot.exe")))
                and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:/(?:program files(?: \(x86\))?/ima[.]copilot|ima[.]copilot|users/[^/]+/appdata/local/ima[.]copilot/application)/ima[.]copilot[.]exe$")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "^tencent technology ?\(shenzhen\) company limited$")))
                and ((remote_host != null and remote_host != "" and (remote_host = "oth.eve.mdt.qq.com"))))), "rpt-ima-mdt;", ""),
         if(((((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:/program files(?: \(x86\))?/(?:manageengine/uems_agent|desktopcentral_agent)/")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "zoho corporation"))))
            or (((_rule_path != null and _rule_path != "" and (_rule_path ~= "^/Library/(?:ManageEngine/UEMS_Agent|Desktopcentral_Agent)/")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "developer id application: zoho corporation"))))), "rpt-manageengine-endpointcentral;", ""),
         if((((_rule_name != null and _rule_name != "" and (_rule_name in ("outlook.exe")))
                and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:/program files(?: \(x86\))?/microsoft office/(?:root/)?office[0-9]+/outlook[.]exe$")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "^microsoft corporation$")))
                and ((remote_host != null and remote_host != "" and (remote_host = "oth.eve.mdt.qq.com"))))), "rpt-outlook-mdt;", ""),
         if((((_rule_name != null and _rule_name != "" and (_rule_name in ("biz_helper.exe", "sgbizlauncher.exe", "pinyinup.exe", "sgtool.exe", "sgsmartassistant.exe", "sogouexe.exe", "sogoucloud.exe", "sogousmartassistant.exe", "biz_aurfx.exe", "sgmyinput.exe", "sgwangzai.exe", "usernetschedule.exe", "crashrpt.exe", "biz_tool.exe", "sgpicfacetool.exe", "wubiup.exe", "imeutil.exe", "wbcrashrpt.exe", "isgpet.exe", "sgiguidehelper.exe", "wbusernetschedule.exe", "write_spirit.exe", "sgwizard.exe", "sogou_voice_assistant.exe", "sgfeedbackhelper.exe")))
                and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:/(?:[^/]+/)*(?:sogouinput|sogouwbinput)/")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "(?:beijing sogou|tencent technology)")))
                and ((remote_host != null and remote_host != "" and (remote_host = "oth.eve.mdt.qq.com"))))), "rpt-sogou-input-mdt;", ""),
         if((((_rule_name != null and _rule_name != "" and (_rule_name in ("yuanbao.exe")))
                and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:/(?:program files(?: \(x86\))?/tencent/yuanbao|users/[^/]+/(?:appdata/(?:local|roaming)/(?:tencent/)?)?yuanbao)/yuanbao[.]exe$")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "^tencent technology ?\(shenzhen\) company limited$")))
                and ((remote_host != null and remote_host != "" and (remote_host = "oth.eve.mdt.qq.com"))))), "rpt-yuanbao-mdt;", "")),
         RetainRuleIds = "",
         CustomerActivityRuleIds = ""
| alter ActivityDecision = if((DefaultRuleIds != "" and RetainRuleIds = "") or CustomerActivityRuleIds != "", "excluded", "retained")
| alter NoiseConflict = if(DetectedToolId != "" and DefaultRuleIds != "" and not(DefaultRuleIds contains "rpt-manageengine-endpointcentral"), true, false)
| alter ActivityDecision=if(CustomerActivityRuleIds != "", "excluded", if(NoiseConflict, "retained", ActivityDecision)),
    EvidenceLevel=if(NoiseConflict or IdentityConflict, "evidence_conflict", EvidenceLevel)
| alter DispositionReason=if(CustomerActivityRuleIds != "", "customer_whitelist", if(NoiseConflict, "identity_noise_conflict",
    if(ActivityDecision = "excluded" and DefaultRuleIds contains "rpt-manageengine-endpointcentral", "report_scope_exclusion",
    if(ActivityDecision = "excluded" and DefaultRuleIds contains "rpt-browser-standard", "browser_report_scope",
    if(ActivityDecision = "excluded", "known_noise", "retained")))))
| alter ReviewCategory = if(_rule_name = "", "process_identity_missing", if(_rule_name = "wwmpapp.exe" and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:.*/wemeet/wwmpapp[.]exe$"))), "meeting_component_candidate", if(remote_host = "oth.eve.mdt.qq.com", "shared_domain_activity", "rmm_domain_activity")))
| filter ActivityDecision = "retained"
| comp min(_time) as first_seen, max(_time) as last_seen, count() as event_count,
       values(actor_primary_username) as usernames, values(actor_effective_username) as effective_usernames,
       values(actor_process_signature_status) as signature_statuses,
       values(actor_process_signature_vendor) as signature_vendors,
       values(actor_process_signature_product) as product_names,
       values(action_local_ip) as local_ips, values(action_remote_ip) as remote_ips,
       values(action_remote_port) as remote_ports, values(actor_process_instance_id) as process_instance_ids,
       values(actor_process_os_pid) as process_ids, values(event_type) as event_types,
       values(event_sub_type) as event_sub_types, values(actor_process_command_line) as command_lines
  by agent_hostname, agent_id, remote_host, actor_process_image_name, actor_process_image_path,
     actor_process_image_sha256, DetectedTool, DetectedToolId, SoftwareRole, IdentityBasis, IdentityIocNames, EvidenceLevel, profile_version, report_status, DispositionReason, ReviewCategory, ActivityDecision, DefaultRuleIds, RetainRuleIds, CustomerActivityRuleIds
| alter _time = first_seen,
        usernames_json = to_json_string(usernames), effective_usernames_json = to_json_string(effective_usernames),
        signature_statuses_json = to_json_string(signature_statuses), signature_vendors_json = to_json_string(signature_vendors),
        product_names_json = to_json_string(product_names),
        local_ips_json = to_json_string(local_ips), remote_ips_json = to_json_string(remote_ips),
        remote_ports_json = to_json_string(remote_ports), process_instance_ids_json = to_json_string(process_instance_ids),
        process_ids_json = to_json_string(process_ids), event_types_json = to_json_string(event_types),
        event_sub_types_json = to_json_string(event_sub_types), command_lines_json = to_json_string(command_lines)
| join conflict_strategy = left type = inner (
    dataset = lolrmm_domains
    | filter domain != null and domain != ""
    | alter domain = lowercase(rtrim(domain, "."))
    | fields domain, rmm_tool, pattern
) as rmm
  remote_host = rmm.domain or wildcard_match(remote_host, concat("*.", rmm.domain))
| filter wildcard_match(remote_host, pattern)
| alter CustomerAssociationRuleIds = ""
| alter AssociationDecision = if(CustomerAssociationRuleIds != "", "excluded", "retained")
| filter AssociationDecision = "retained"
| comp values(domain) as matched_domains, values(rmm_tool) as rmm_tools, values(pattern) as patterns,
       values(CustomerAssociationRuleIds) as CustomerAssociationRuleIds,
       first(first_seen) as first_seen, first(last_seen) as last_seen, first(event_count) as event_count,
       first(usernames_json) as usernames_json, first(effective_usernames_json) as effective_usernames_json,
       first(signature_statuses_json) as signature_statuses_json, first(signature_vendors_json) as signature_vendors_json,
       first(product_names_json) as product_names_json,
       first(local_ips_json) as local_ips_json, first(remote_ips_json) as remote_ips_json,
       first(remote_ports_json) as remote_ports_json, first(process_instance_ids_json) as process_instance_ids_json,
       first(process_ids_json) as process_ids_json, first(event_types_json) as event_types_json,
       first(event_sub_types_json) as event_sub_types_json, first(command_lines_json) as command_lines_json
  by agent_hostname, agent_id, remote_host, actor_process_image_name, actor_process_image_path,
     actor_process_image_sha256, DetectedTool, DetectedToolId, SoftwareRole, IdentityBasis, IdentityIocNames, EvidenceLevel, profile_version, report_status, DispositionReason, ReviewCategory, ActivityDecision, DefaultRuleIds, RetainRuleIds,
     CustomerActivityRuleIds, AssociationDecision
| alter usernames = json_extract_scalar_array(usernames_json, "$"),
        effective_usernames = json_extract_scalar_array(effective_usernames_json, "$"),
        signature_statuses = arraymap(json_extract_scalar_array(signature_statuses_json, "$"), to_integer("@element")),
        signature_vendors = json_extract_scalar_array(signature_vendors_json, "$"),
        product_names = json_extract_scalar_array(product_names_json, "$"),
        local_ips = json_extract_scalar_array(local_ips_json, "$"), remote_ips = json_extract_scalar_array(remote_ips_json, "$"),
        remote_ports = arraymap(json_extract_scalar_array(remote_ports_json, "$"), to_integer("@element")),
        process_instance_ids = json_extract_scalar_array(process_instance_ids_json, "$"),
        process_ids = arraymap(json_extract_scalar_array(process_ids_json, "$"), to_integer("@element")),
        event_types = arraymap(json_extract_scalar_array(event_types_json, "$"), to_integer("@element")),
        event_sub_types = arraymap(json_extract_scalar_array(event_sub_types_json, "$"), to_integer("@element")),
        command_lines = json_extract_scalar_array(command_lines_json, "$")
| alter ioc_related_tools = rmm_tools, match_basis = if(DetectedToolId != "", "domain+identity", "domain"),
        signature_evidence_source = "actor_event"
| fields agent_hostname, agent_id, DetectedTool, DetectedToolId, SoftwareRole, IdentityBasis, IdentityIocNames, EvidenceLevel, profile_version, report_status, DispositionReason, ReviewCategory, actor_process_image_name, product_names, ioc_related_tools,
         match_basis, remote_host, matched_domains, patterns, rmm_tools,
         first_seen, last_seen, event_count, actor_process_image_path,
         actor_process_image_sha256, signature_statuses, signature_vendors, command_lines,
         usernames, effective_usernames, process_instance_ids, process_ids, remote_ips,
         remote_ports, local_ips, event_types, event_sub_types, signature_evidence_source

| union (dataset = rmm_tool_profiles
    | filter release in (dataset = rmm_tool_profiles | filter record_type = "manifest" | sort desc release | limit 1 | fields release)
    | comp count() as _profile_rows, count_distinct(process_name) as _profile_keys,
        count_distinct(release_digest) as _profile_digests,
        sum(if(record_type = "manifest", 1, 0)) as _profile_markers,
        max(to_integer(expected_rows)) as _expected_rows, max(release) as profile_version
    | alter ProfileOK = if(_profile_rows = add(_expected_rows, 1) and _profile_keys = add(_expected_rows, 1)
        and _expected_rows > 0 and _profile_markers = 1 and _profile_digests = 1, true, false)
    | alter report_status = if(ProfileOK = true, "ok", "profile_data_unavailable"), _health_key = 1
| filter report_status != "ok" | fields report_status, profile_version)
| alter ReportSection=if(report_status != "ok", "data_error", if(EvidenceLevel = "supported_identity" and SoftwareRole = "rmm", "main", "review"))
| filter report_status != "ok" or ReportSection = "main"
| sort desc last_seen
