// Generated by scripts/build_rmm_queries.py; rules 1.0.0; mode report.
// Rule SHA256: de68af0ab2b5bad5e422c27820eacae27def422806717d12797f9c992f63910d; config SHA256: f75c4ff1f69b813a1e3170e2d0d903a16469c914750766db5e062f1ce5a26f2f.
// Event counts precede IOC association; collection fields are independent sets.
// Official references and usage: README.md. Validate Cortex with a 1h window.
config case_sensitive = true timeframe = 7d
| dataset = xdr_data
| filter action_external_hostname != null
| alter remote_host = lowercase(rtrim(action_external_hostname, ".")),
        _rule_name = lowercase(coalesce(actor_process_image_name, "")),
        _rule_path = if(actor_process_image_path ~= "^[A-Za-z]:", lowercase(replex(actor_process_image_path, "[\\\\]", "/")), coalesce(actor_process_image_path, "")),
        _rule_signer = lowercase(coalesce(actor_process_signature_vendor, "")),
        _rule_device_name = lowercase(coalesce(agent_hostname, "")),
        _rule_sha256 = lowercase(coalesce(actor_process_image_sha256, "")),
        _signature_valid = if(actor_process_signature_status = null, null, if(actor_process_signature_status = 1, true, false))
| filter remote_host != ""
| alter DefaultRuleIds = concat(if(((((_rule_name != null and _rule_name != "" and (_rule_name = "chrome.exe")))
                and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:/(?:program files(?: \(x86\))?|users/[^/]+/appdata/(?:local|roaming))/(?:[^/]+/)*google/(?:[^/]+/)*chrome[.]exe$")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "google (?:llc|inc)"))))
            or (((_rule_name != null and _rule_name != "" and (_rule_name = "msedge.exe")))
                and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:/(?:program files(?: \(x86\))?|users/[^/]+/appdata/(?:local|roaming))/(?:[^/]+/)*microsoft/edge/(?:[^/]+/)*msedge[.]exe$")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "microsoft corporation"))))
            or (((_rule_name != null and _rule_name != "" and (_rule_name = "firefox.exe")))
                and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:/(?:program files(?: \(x86\))?|users/[^/]+/appdata/(?:local|roaming))/(?:[^/]+/)*mozilla firefox/(?:[^/]+/)*firefox[.]exe$")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "mozilla corporation"))))
            or (((_rule_name != null and _rule_name != "" and (_rule_name = "vivaldi.exe")))
                and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:/(?:program files(?: \(x86\))?|users/[^/]+/appdata/(?:local|roaming))/(?:[^/]+/)*vivaldi/(?:[^/]+/)*vivaldi[.]exe$")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "vivaldi technologies"))))
            or (((_rule_name != null and _rule_name != "" and (_rule_name = "qqbrowser.exe")))
                and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:/(?:program files(?: \(x86\))?|users/[^/]+/appdata/(?:local|roaming))/(?:[^/]+/)*tencent/qqbrowser/(?:[^/]+/)*qqbrowser[.]exe$")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "tencent technology"))))), "rpt-browser-standard;", ""),
         if(((((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:/program files(?: \(x86\))?/(?:manageengine/uems_agent|desktopcentral_agent)/")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "zoho corporation"))))
            or (((_rule_path != null and _rule_path != "" and (_rule_path ~= "^/Library/(?:ManageEngine/UEMS_Agent|Desktopcentral_Agent)/")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "developer id application: zoho corporation"))))), "rpt-manageengine-endpointcentral;", ""),
         if(((((_rule_name != null and _rule_name != "" and (_rule_name = "biz_helper.exe")) or (_rule_name != null and _rule_name != "" and (_rule_name = "sgbizlauncher.exe")) or (_rule_name != null and _rule_name != "" and (_rule_name = "pinyinup.exe")) or (_rule_name != null and _rule_name != "" and (_rule_name = "sgtool.exe")) or (_rule_name != null and _rule_name != "" and (_rule_name = "sgsmartassistant.exe")) or (_rule_name != null and _rule_name != "" and (_rule_name = "sogouexe.exe")) or (_rule_name != null and _rule_name != "" and (_rule_name = "sogoucloud.exe")) or (_rule_name != null and _rule_name != "" and (_rule_name = "sogousmartassistant.exe")) or (_rule_name != null and _rule_name != "" and (_rule_name = "biz_aurfx.exe")) or (_rule_name != null and _rule_name != "" and (_rule_name = "sgmyinput.exe")) or (_rule_name != null and _rule_name != "" and (_rule_name = "sgwangzai.exe")) or (_rule_name != null and _rule_name != "" and (_rule_name = "usernetschedule.exe")) or (_rule_name != null and _rule_name != "" and (_rule_name = "crashrpt.exe")) or (_rule_name != null and _rule_name != "" and (_rule_name = "biz_tool.exe")) or (_rule_name != null and _rule_name != "" and (_rule_name = "sgpicfacetool.exe")) or (_rule_name != null and _rule_name != "" and (_rule_name = "wubiup.exe")) or (_rule_name != null and _rule_name != "" and (_rule_name = "imeutil.exe")) or (_rule_name != null and _rule_name != "" and (_rule_name = "wbcrashrpt.exe")))
                and ((_rule_path != null and _rule_path != "" and (_rule_path ~= "^[a-z]:/(?:[^/]+/)*(?:sogouinput|sogouwbinput)/")))
                and ((_signature_valid != null and (_signature_valid = true)))
                and ((_rule_signer != null and _rule_signer != "" and (_rule_signer ~= "(?:beijing sogou|tencent technology)")))
                and ((remote_host != null and remote_host != "" and (remote_host = "oth.eve.mdt.qq.com"))))), "rpt-sogou-input-mdt;", "")),
         RetainRuleIds = "",
         CustomerActivityRuleIds = ""
| alter ActivityDecision = if((DefaultRuleIds != "" and RetainRuleIds = "") or CustomerActivityRuleIds != "", "excluded", "retained")
| filter ActivityDecision = "retained"
| comp min(_time) as first_seen, max(_time) as last_seen, count() as event_count,
       values(actor_primary_username) as usernames, values(actor_effective_username) as effective_usernames,
       values(actor_process_signature_status) as signature_statuses,
       values(actor_process_signature_vendor) as signature_vendors,
       values(action_local_ip) as local_ips, values(action_remote_ip) as remote_ips,
       values(action_remote_port) as remote_ports, values(actor_process_instance_id) as process_instance_ids,
       values(actor_process_os_pid) as process_ids, values(event_type) as event_types,
       values(event_sub_type) as event_sub_types, values(actor_process_command_line) as command_lines
  by agent_hostname, agent_id, remote_host, actor_process_image_name, actor_process_image_path,
     actor_process_image_sha256, ActivityDecision, DefaultRuleIds, RetainRuleIds, CustomerActivityRuleIds
| alter _time = first_seen,
        usernames_json = to_json_string(usernames), effective_usernames_json = to_json_string(effective_usernames),
        signature_statuses_json = to_json_string(signature_statuses), signature_vendors_json = to_json_string(signature_vendors),
        local_ips_json = to_json_string(local_ips), remote_ips_json = to_json_string(remote_ips),
        remote_ports_json = to_json_string(remote_ports), process_instance_ids_json = to_json_string(process_instance_ids),
        process_ids_json = to_json_string(process_ids), event_types_json = to_json_string(event_types),
        event_sub_types_json = to_json_string(event_sub_types), command_lines_json = to_json_string(command_lines)
| join conflict_strategy = left type = inner (
    dataset = lolrmm_domains
    | filter domain != null and domain != ""
    | alter domain = lowercase(rtrim(domain, "."))
    | fields domain, rmm_tool, pattern
) as rmm
  remote_host = rmm.domain or wildcard_match(remote_host, concat("*.", rmm.domain))
| alter CustomerAssociationRuleIds = ""
| alter AssociationDecision = if(CustomerAssociationRuleIds != "", "excluded", "retained")
| filter AssociationDecision = "retained"
| comp values(domain) as matched_domains, values(rmm_tool) as rmm_tools, values(pattern) as patterns,
       values(CustomerAssociationRuleIds) as CustomerAssociationRuleIds,
       first(first_seen) as first_seen, first(last_seen) as last_seen, first(event_count) as event_count,
       first(usernames_json) as usernames_json, first(effective_usernames_json) as effective_usernames_json,
       first(signature_statuses_json) as signature_statuses_json, first(signature_vendors_json) as signature_vendors_json,
       first(local_ips_json) as local_ips_json, first(remote_ips_json) as remote_ips_json,
       first(remote_ports_json) as remote_ports_json, first(process_instance_ids_json) as process_instance_ids_json,
       first(process_ids_json) as process_ids_json, first(event_types_json) as event_types_json,
       first(event_sub_types_json) as event_sub_types_json, first(command_lines_json) as command_lines_json
  by agent_hostname, agent_id, remote_host, actor_process_image_name, actor_process_image_path,
     actor_process_image_sha256, ActivityDecision, DefaultRuleIds, RetainRuleIds,
     CustomerActivityRuleIds, AssociationDecision
| alter usernames = json_extract_scalar_array(usernames_json, "$"),
        effective_usernames = json_extract_scalar_array(effective_usernames_json, "$"),
        signature_statuses = arraymap(json_extract_scalar_array(signature_statuses_json, "$"), to_integer("@element")),
        signature_vendors = json_extract_scalar_array(signature_vendors_json, "$"),
        local_ips = json_extract_scalar_array(local_ips_json, "$"), remote_ips = json_extract_scalar_array(remote_ips_json, "$"),
        remote_ports = arraymap(json_extract_scalar_array(remote_ports_json, "$"), to_integer("@element")),
        process_instance_ids = json_extract_scalar_array(process_instance_ids_json, "$"),
        process_ids = arraymap(json_extract_scalar_array(process_ids_json, "$"), to_integer("@element")),
        event_types = arraymap(json_extract_scalar_array(event_types_json, "$"), to_integer("@element")),
        event_sub_types = arraymap(json_extract_scalar_array(event_sub_types_json, "$"), to_integer("@element")),
        command_lines = json_extract_scalar_array(command_lines_json, "$")
| fields agent_hostname, agent_id, rmm_tools, remote_host, matched_domains, patterns,
         first_seen, last_seen, event_count, actor_process_image_name, actor_process_image_path,
         actor_process_image_sha256, signature_statuses, signature_vendors, command_lines,
         usernames, effective_usernames, process_instance_ids, process_ids, remote_ips,
         remote_ports, local_ips, event_types, event_sub_types
| sort desc last_seen
